apiVersion: v1
entries:
  kafka-exporter:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-01-21T09:32:03.75305041+01:00"
    description: A Helm chart for Kubernetes
    digest: 9c7d1ae9395ebaa729019f447dbc4da49eb9004557ab6661e9a70a74b62db6db
    home: https://github.com/abhishekjiitr/kafka-exporter-helm
    maintainers:
    - email: abhi2254015@gmail.com
      name: abhishekjiitr
    name: kafka-exporter
    urls:
    - kafka-exporter/kafka-exporter-1.0.3.tgz
    version: 1.0.3
generated: "2020-01-21T09:32:03.75265773+01:00"
